Algoritmo "Saudação"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/06/2019
Var
// Seção de Declarações das variáveis 
 nome: Caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreva ("Digite seu nome: ")
 leia (nome)
 
 escreva ("seja bem vindo(a), ", nome)

Fimalgoritmo