Algoritmo "semnome"

Var
numUm, numDois: real

Inicio
escreva("Digite o primeiro valor: ")
leia (numUm)

escreva("Digite o segundo valor: ")
leia(numDois)

escreval("A soma dos valores digitados é de: ",numUm + numDois)
escreval("A subtração dos valores digitados é de: ", numUm - numDois)
escreval("A soma dos valores digitados é de: ", numUm * numDois)
escreval("A soma dos valores digitados é de: ", numUm / numDois)


Fimalgoritmo